### ISSUE TITLE
Upgrade to Launchdarkly Python SDK 8.X?

### ISSUE THREAD

**Issue by bdstout** [z3z1ma/dbt-feature-flags#1]
Hi @z3z1ma,
Any chance launchdarkly can be upgraded to support the 8.X SDK? I know this repo has been dormant but thought I would ask.

**Comment by z3z1ma** [comment]
Sure can do. I would say it's inactive only because there isn't much more to do functionally. It does what's advertised. That being said we should probably get dependabot and a test matrix going.

**Comment by z3z1ma** [comment]
@bdstout done. Will push pypi release tomorrow.

**Comment by bdstout** [comment]
@z3z1ma https://docs.launchdarkly.com/sdk/server-side/python

Based on that link, I think the launchdarkly code requires a new version for using the new SDK. Thoughts?
